// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqkmjtRshOdB11u6l88KktLDXuqKhtF40',
    appId: '1:771152336512:web:bd2e8975132f789b9d7865',
    messagingSenderId: '771152336512',
    projectId: 'myfirst-ashish',
    authDomain: 'myfirst-ashish.firebaseapp.com',
    storageBucket: 'myfirst-ashish.firebasestorage.app',
    measurementId: 'G-XCF1D50PKP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcI_WIFACYXdPMDNapAqDX55tyvuxCzLU',
    appId: '1:771152336512:android:ba9c06a8e8c3ac519d7865',
    messagingSenderId: '771152336512',
    projectId: 'myfirst-ashish',
    storageBucket: 'myfirst-ashish.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkv0AWIIO9D3RTqaTprT7b7wkpSMxhYwM',
    appId: '1:771152336512:ios:a3a53fed35423a679d7865',
    messagingSenderId: '771152336512',
    projectId: 'myfirst-ashish',
    storageBucket: 'myfirst-ashish.firebasestorage.app',
    iosBundleId: 'com.ashish.firstapplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkv0AWIIO9D3RTqaTprT7b7wkpSMxhYwM',
    appId: '1:771152336512:ios:a3a53fed35423a679d7865',
    messagingSenderId: '771152336512',
    projectId: 'myfirst-ashish',
    storageBucket: 'myfirst-ashish.firebasestorage.app',
    iosBundleId: 'com.ashish.firstapplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqkmjtRshOdB11u6l88KktLDXuqKhtF40',
    appId: '1:771152336512:web:93892ff0a70dfa469d7865',
    messagingSenderId: '771152336512',
    projectId: 'myfirst-ashish',
    authDomain: 'myfirst-ashish.firebaseapp.com',
    storageBucket: 'myfirst-ashish.firebasestorage.app',
    measurementId: 'G-5XL6R0ZH0S',
  );
}
